blueprint:
  name: Motion-triggered Lights with Timer
  description: >
    Automatically turns lights on/off based on motion, light state, timers, and conditions. 
    Requires a motion sensor entity, a light entity (a light group works for multiple lights), a timer 
    entity (with the time set in its configuration), and two input_boolean helpers that you must create - 
    one that controls whether the lights will be turned on automatically when motion is detected 
    (e.g. input_boolean.deck_lights_auto_on_controller) and one to control whether the lights are 
    turned off when the timer ends (e.g. input_boolean.deck_lights_auto_off_controller).
  domain: automation
  author: Scott Menzer
  input:
    trigger_sensor:
      name: Trigger Sensor
      description: "The trigger sensor (motion, occupancy, etc.) that triggers the lights."
      selector:
        entity:
          filter:
            domain: 
              - binary_sensor
              - input_boolean
    light_target:
      name: Light
      description: "The light entity to control."
      selector:
        entity:
          filter:
            domain: light
    auto_on_controller:
      name: Auto On Controller Entity
      description: "Boolean to enable/disable automatic turning on of the lights."
      selector:
        entity:
          filter:
            domain: input_boolean
    only_when_sun_is_down:
      name: Auto On Only When Sun is Down
      description: "Enable to only turn on lights when motion is detected when the sun is down (according to sun integration). Disable to turn on lights any time motion is detected."
      selector:
        boolean:
      default: true
    auto_off_controller:
      name: Auto Off Controller Entity
      description: "Boolean to enable/disable automatic turning off of the lights."
      selector:
        entity:
          filter:
            domain: input_boolean
    auto_off_timer:
      name: Timer
      description: "Timer entity to delay turning off the lights."
      selector:
        entity:
          filter:
            domain: timer
    off_transition:
      name: Time Off Transition
      description: >
        Brightness off transition
      default: 60
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds

variables:
  only_when_sun_is_down: !input only_when_sun_is_down

triggers:
  - trigger: state
    entity_id: !input trigger_sensor
    id: trigger-on
    to: "on"
  - trigger: state
    entity_id: !input trigger_sensor
    id: trigger-off
    to: "off"
  - trigger: state
    entity_id: !input light_target
    to: "on"
    id: light-on
  - trigger: state
    entity_id: !input light_target
    to: "off"
    from: "on"
    id: light-off
  - trigger: state
    entity_id: !input auto_off_controller
    to: "on"
    id: auto-off-enabled
  - trigger: state
    entity_id: !input auto_off_controller
    to: "off"
    id: auto-off-disabled
  - trigger: event
    event_data:
      entity_id: !input auto_off_timer
    event_type: timer.finished
    id: timer-end

conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - trigger-on
        sequence:
          # check if auto-on is enabled
        - condition: state
          entity_id: !input auto_on_controller
          state: "on"
        - condition: state
          entity_id: !input light_target
          state: "off"
          # if after sunset or the sun_down toggle is off
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
              after: sunset
            - condition: template
              value_template: >
                {{ only_when_sun_is_down == false }}
          # turn on the light(s)
        - action: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: !input light_target

        # light-on and trigger-off will start the timer, if needed
      - conditions:
          - condition: trigger
            id:
              - light-on
              - trigger-off
              - auto-off-enabled
        sequence:
          # conditions: auto-off enabled, sensor off, and light is on
          # action: start the timer
          - condition: state
            entity_id: !input auto_off_controller
            state: "on"
          - condition: state
            entity_id: !input trigger_sensor
            state: "off"
          - condition: state
            entity_id: !input light_target
            state: "on"
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: !input auto_off_timer
        # if the light turns off outside automation - or auto-off toggle is disabled, cancel timer
      - conditions:
          - condition: trigger
            id:
              - light-off
              - auto-off-disabled
        sequence:
          - action: timer.cancel
            metadata: {}
            data: {}
            target:
              entity_id: !input auto_off_timer
      - conditions:
          - condition: trigger
            id:
              - timer-end
        sequence:
          - condition: state
            entity_id: !input light_target
            state: "on"
          - condition: state
            entity_id: !input trigger_sensor
            state: "off"
          - condition: state
            entity_id: !input auto_off_controller
            state: "on"
          - action: light.turn_off
            metadata: {}
            data:
              entity_id: !input light_target
              transition: !input off_transition
            #target:
            #  entity_id: !input light_target

mode: restart
max_exceeded: silent